{% set name = "yaqd-system-monitor" %}
{% set version = "2021.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 161a44af2249b058fe1c7c6d70bd192bd2bc6d143c9e3e5d6e0b48044de543e6

build:
  number: 0
  noarch: python
  entry_points:
    - yaqd-system-monitor = yaqd_system_monitor._system_monitor:SystemMonitor.main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - psutil
    - uptime
    - yaqd-core >=2021.3.0
    - flit
    - python >=3.7
  run:
    - psutil
    - python >=3.7
    - uptime
    - yaqd-core >=2021.3.0

test:
  imports:
    - yaqd_system_monitor
  commands:
    - pip check
    - yaqd-system-monitor --help
  requires:
    - pip

about:
  home: https://yaq.fyi
  summary: yaq daemon for monitoring system usage
  dev_url: https://gitlab.com/yaq/yaqd-control
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - untzag
    - ksunden
